FROM --platform=$TARGETPLATFORM ghcr.io/ksmartdata/rclone-redis:v0.1.3 as all

USER root

COPY rootfs/usr/local/bin/docker-entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/docker-entrypoint.sh