FROM --platform=$TARGETPLATFORM quay.io/opstree/redis:v5.0.5

COPY redis.conf /etc/redis/redis.conf

COPY entrypoint.sh /usr/bin/entrypoint.sh

COPY setupMasterSlave.sh /usr/bin/setupMasterSlave.sh

COPY healthcheck.sh /usr/bin/healthcheck.sh

RUN mkdir -p /opt/redis/ && chmod -R g+rwX /etc/redis /opt/redis

RUN chmod +x /usr/bin/entrypoint.sh
RUN chmod +x /usr/bin/setupMasterSlave.sh
RUN chmod +x /usr/bin/healthcheck.sh

VOLUME ["/data"]

WORKDIR /data

EXPOSE 6379 6379

ENTRYPOINT ["/usr/bin/entrypoint.sh"]